[tool.black]
line-length = 120
# required-version = '22.1.0' # see https://github.com/psf/black/issues/2493
target-version = ['py310']


[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
show_error_codes = true
